### PR TITLE
feat(fe): refine app folder

### LINKED ISSUE #425: The menu item "Open App folder" uses a dialog similar to a file manager, allowing users to select the folder they want to open

### PR DESCRIPTION
**Pull request by shczhen**
## Related Issue

https://github.com/TEN-framework/ten_framework/issues/425

## Purpose

New three cols app folder

image

## Checklist

- [x] components ready
- [x] apply API: get file system details from backend
- [x] remove mock data
- [x] apply `enum` for file/folder items

### CODE REVIEW

**Comment by halajohn** [comment]
有 conflict

**Comment by halajohn** [comment]
merge 了另一笔 PR, 这笔有 conflict 了

**Comment by halajohn** [comment]
npm run build 会有底下 11 个错误

src/api/endpoints/addons.ts:1:15 - error TS2307: Cannot find module 'zod' or its corresponding type declarations.

1 import z from "zod";
                ~~~~~

src/api/endpoints/fileSystem.ts:1:15 - error TS2307: Cannot find module 'zod' or its corresponding type declarations.

1 import z from "zod";
                ~~~~~

src/api/endpoints/graphs.ts:1:15 - error TS2307: Cannot find module 'zod' or its corresponding type declarations.

1 import z from "zod";
                ~~~~~

src/api/endpoints/index.ts:1:15 - error TS2307: Cannot find module 'zod' or its corresponding type declarations.

1 import z from "zod";
                ~~~~~

src/api/endpoints/utils.ts:1:15 - error TS2307: Cannot find module 'zod' or its corresponding type declarations.

1 import z from "zod";
                ~~~~~

src/api/services/common.ts:1:15 - error TS2307: Cannot find module 'zod' or its corresponding type declarations.

1 import z from "zod";
                ~~~~~

src/api/services/fileSystem.ts:1:15 - error TS2307: Cannot find module 'zod' or its corresponding type declarations.

1 import z from "zod";
                ~~~~~

src/api/services/utils.ts:1:65 - error TS2307: Cannot find module 'swr' or its corresponding type declarations.

1 import useSWR, { type SWRResponse, type SWRConfiguration } from "swr";
                                                                  ~~~~~

src/logger/index.ts:1:18 - error TS2307: Cannot find module 'pino' or its corresponding type declarations.

1 import pino from "pino";
                   ~~~~~~

src/logger/index.ts:16:15 - error TS7006: Parameter 'label' implicitly has an 'any' type.

16       level: (label) => ({ level: label }),
                 ~~~~~

src/logger/index.ts:17:15 - error TS7031: Binding element 'time' implicitly has an 'any' type.

17       log: ({ time, ...object }) => ({
                 ~~~~


Found 11 errors.

**Comment by shczhen** [comment]
> npm run build 会有底下 11 个错误
> 
> src/api/endpoints/addons.ts:1:15 - error TS2307: Cannot find module 'zod' or its corresponding type declarations.
> 
> 1 import z from "zod"; ~~~~~
> 
> src/api/endpoints/fileSystem.ts:1:15 - error TS2307: Cannot find module 'zod' or its corresponding type declarations.
> 
> 1 import z from "zod"; ~~~~~
> 
> src/api/endpoints/graphs.ts:1:15 - error TS2307: Cannot find module 'zod' or its corresponding type declarations.
> 
> 1 import z from "zod"; ~~~~~
> 
> src/api/endpoints/index.ts:1:15 - error TS2307: Cannot find module 'zod' or its corresponding type declarations.
> 
> 1 import z from "zod"; ~~~~~
> 
> src/api/endpoints/utils.ts:1:15 - error TS2307: Cannot find module 'zod' or its corresponding type declarations.
> 
> 1 import z from "zod"; ~~~~~
> 
> src/api/services/common.ts:1:15 - error TS2307: Cannot find module 'zod' or its corresponding type declarations.
> 
> 1 import z from "zod"; ~~~~~
> 
> src/api/services/fileSystem.ts:1:15 - error TS2307: Cannot find module 'zod' or its corresponding type declarations.
> 
> 1 import z from "zod"; ~~~~~
> 
> src/api/services/utils.ts:1:65 - error TS2307: Cannot find module 'swr' or its corresponding type declarations.
> 
> 1 import useSWR, { type SWRResponse, type SWRConfiguration } from "swr"; ~~~~~
> 
> src/logger/index.ts:1:18 - error TS2307: Cannot find module 'pino' or its corresponding type declarations.
> 
> 1 import pino from "pino"; ~~~~~~
> 
> src/logger/index.ts:16:15 - error TS7006: Parameter 'label' implicitly has an 'any' type.
> 
> 16 level: (label) => ({ level: label }), ~~~~~
> 
> src/logger/index.ts:17:15 - error TS7031: Binding element 'time' implicitly has an 'any' type.
> 
> 17 log: ({ time, ...object }) => ({ ~~~~
> 
> Found 11 errors.

Need to install missing dependencies first. Such as:

```bash
bun i
```

**Pull request merged**
